name: Build and test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  buildAndTest:
    name: Build and test (Node.js v${{ matrix.node-version }})
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16.5.0]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm i pnpm@latest -g
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build:ci
      - name: Test packages
        run: pnpm run test:ci
