name: Build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:    
jobs:
  buildAndTest:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        run: npm i pnpm@latest -g
      - name: Build packages
        run: pnpm run build:ci
      - name: Test packages
        run: pnpm run test:ci
